//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crime()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string State { get; set; }
        public double Population { get; set; }
        public double Violent_Crime { get; set; }
        public double Homicide { get; set; }
        public double Rape_Revised { get; set; }
        public double Robbery { get; set; }
        public double Aggravated_Assault { get; set; }
        public double Property_Crime { get; set; }
        public double Burglary { get; set; }
        public double Larceny { get; set; }
        public double Motor_Vehicle_Theft { get; set; }
        public double Arson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }

        //////////////////////
        ///How we got states//
        //////////////////////
        //string[] states = { "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI",
        //                    "ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI",
        //                    "MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC",
        //                    "ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT",
        //                    "VT","VA","WA","WV","WI","WY" };

        //for(int i = 0; i < states.Length; i++)
        //{
        //    Crime crime = new Crime(states[i]);
        //    ORM.Crimes.Add(crime);

        #region Constructors
       /* public Crime(string state)
        {
            JObject allData = JObject.Parse(GetStateData(state));
            JObject data = (JObject)(allData["results"].Where(s => (int)s["year"] == 2017).First());


            State = (string)(data)["state_abbr"];
            Population = (double?)(data)["population"] ?? 0;
            Violent_Crime = (double?)(data)["violent_crime"] ?? 0;
            Homicide = (double?)(data)["homicide"] ?? 0;

            Rape_Revised = (double?)(data)["rape_revised"] ?? 0;
            Robbery = (double?)(data)["robbery"] ?? 0;
            Aggravated_Assault = (double?)(data)["aggravated_assault"] ?? 0;
            Property_Crime = (double?)(data)["property_crime"] ?? 0;

            Burglary = (double?)(data)["burglary"] ?? 0;
            Larceny = (double?)(data)["larceny"] ?? 0;
            Motor_Vehicle_Theft = (double?)(data)["motor_vehicle_theft"] ?? 0;
            Arson = (double?)(data)["arson"] ?? 0;


        }
        public Crime()
        {

        }*/
        #endregion

        #region DAL Info/Methods
        /*private static string apiKey = ConfigurationManager.AppSettings["apiKey"];

        public static string GetStateData(string state)
        {
            HttpWebRequest request = WebRequest.CreateHttp($"https://api.usa.gov/crime/fbi/sapi/api/estimates/states/{state}/2000/2017?api_key={apiKey}");

            request.UserAgent = "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0";

            HttpWebResponse response = (HttpWebResponse)request.GetResponse();

            if (response.StatusCode == HttpStatusCode.OK)
            {
                StreamReader data = new StreamReader(response.GetResponseStream());
                return data.ReadToEnd();
            }
            return null;
        }*/
        #endregion
    }
}
