//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;

    public partial class Crime
    {
        public string State { get; set; }
        public double Population { get; set; }
        public double Violent_Crime { get; set; }
        public double Homicide { get; set; }
        public double Rape_Revised { get; set; }
        public double Robbery { get; set; }
        public double Aggravated_Assault { get; set; }
        public double Property_Crime { get; set; }
        public double Burglary { get; set; }
        public double Larceny { get; set; }
        public double Motor_Vehicle_Theft { get; set; }
        public double Arson { get; set; }


        #region Constructors
        public Crime(string state)
        {
            JObject allData = JObject.Parse(GetStateData(state));
            JObject data = (JObject)(allData["results"].Where(s => (int)s["year"] == 2017).First());


            State = (string)(data)["state_abbr"];
            Population = (double?)(data)["population"] ?? 0;
            Violent_Crime = (double?)(data)["violent_crime"] ?? 0;
            Homicide = (double?)(data)["homicide"] ?? 0;

            Rape_Revised = (double?)(data)["rape_revised"] ?? 0;
            Robbery = (double?)(data)["robbery"] ?? 0;
            Aggravated_Assault = (double?)(data)["aggravated_assault"] ?? 0;
            Property_Crime = (double?)(data)["property_crime"] ?? 0;

            Burglary = (double?)(data)["burglary"] ?? 0;
            Larceny = (double?)(data)["larceny"] ?? 0;
            Motor_Vehicle_Theft = (double?)(data)["motor_vehicle_theft"] ?? 0;
            Arson = (double?)(data)["arson"] ?? 0;


        }
        public Crime()
        {

        }
        #endregion

        #region DAL Info/Methods
        private static string apiKey = ConfigurationManager.AppSettings["apiKey"];

        public static string GetStateData(string state)
        {
            HttpWebRequest request = WebRequest.CreateHttp($"https://api.usa.gov/crime/fbi/sapi/api/estimates/states/{state}/2000/2017?api_key={apiKey}");

            request.UserAgent = "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0";

            HttpWebResponse response = (HttpWebResponse)request.GetResponse();

            if (response.StatusCode == HttpStatusCode.OK)
            {
                StreamReader data = new StreamReader(response.GetResponseStream());
                return data.ReadToEnd();
            }
            return null;
        }
        #endregion

    }

}
