//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mentor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Personality { get; set; }
        public string Ability1 { get; set; }
        public string Ability2 { get; set; }
        public bool Hero_Villain { get; set; }
    }
}
